apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2bcloud
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - command:
         - kubelet
         - --anonymous-auth=false
      - name: node
        image: elchananmizrachi/2bcloud:__TAG__
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
